# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # if you don't do these things before calling goreleaser, it might be a
    # good idea to do them here:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - id: zdir
    builder: rust
    binary: "zdir"
    flags:
      - --release
      - --package=zdir
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
  - id: zdir-librarian
    builder: rust
    binary: "zdir-librarian"
    flags:
      - --release
      - --package=zdir-librarian
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl

archives:
  - id: "zdir"
    formats: [binary]
    builds:
      - zdir
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
  - id: "zdir-librarian"
    formats: [binary]
    builds:
      - zdir-librarian
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
